In [ ]:
import cv2 as cv2   #importing opevcv
import numpy as np


symp_im = cv2.imread('symptoms/11085_right.jpeg');    #reading an image
I = symp_im.copy()
grayScale_symp_im = cv2.cvtColor(symp_im, cv2.COLOR_BGR2GRAY);  #converting the orginal image to GRAY SCALE


#RESIZE IMAGE
#symp_im_rs = cv2.resize(symp_im, (1430, 720));     #orginal image resizing
#gray_symp_im_rs = cv2.resize(grayScale_symp_im, (430, 320));    #grayscale image resizing

#SHOWING IMAGE
#cv2.imshow('symptoms image',symp_im_rs);    #orginal image
#cv2.imshow('Gray Scale - symptoms image',gray_symp_im_rs);    #gryascale image


#BINARISING & THRESHOLD SLIDER
#threshold slider code
#nothing() is called each time threshold value is updated

ret,thresh_symp_im = cv2.threshold(grayScale_symp_im, 135, 255, cv2.THRESH_BINARY_INV);   #binarising based on threshold slider
    
#contour drawing test code
image, contours, hierarchy = cv2.findContours(thresh_symp_im, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

img = cv2.drawContours(image, contours, -1, (0,0, 255), 3)

for contour in contours:
    print contour

    original = cv2.boundingRect(contour)

        
    cv2.rectangle(symp_im, (original[0], original[1]), (original[0]+original[2], original[1] + original[3]), (0,0,255), 3)
#img = cv2.putText(image, str("s"), cv2.boundingRect(contour)[:2], cv2.FONT_HERSHEY_COMPLEX, 1, [125])
#test code ends here
bin_symp_im_rs = cv2.resize(symp_im, (900, 720));    #Binary image resizing
cv2.imshow('Binarised.png', bin_symp_im_rs);    #show binary image

    


#keyboard binding function
k = cv2.waitKey(0);   
if k == 27:           #wait for ESC key to exit
    cv2.destroyAllWindows();     #destroys all windows created

[[[1908 1918]]

 [[1907 1919]]

 [[1911 1919]]

 [[1910 1918]]]
[[[ 960 1917]]

 [[ 959 1918]]

 [[ 956 1918]]

 [[ 956 1919]]

 [[ 959 1919]]

 [[ 960 1918]]

 [[ 961 1918]]

 [[ 961 1917]]]
[[[1687 1916]]

 [[1686 1917]]

 [[1686 1919]]

 [[1689 1919]]

 [[1689 1917]]

 [[1688 1916]]]
[[[1104 1916]]

 [[1104 1918]]

 [[1103 1919]]

 [[1102 1918]]

 [[1102 1917]]

 [[1099 1917]]

 [[1099 1919]]

 [[1105 1919]]

 [[1105 1917]]]
[[[1925 1912]]]
[[[1920 1912]]

 [[1921 1912]]

 [[1922 1913]]

 [[1920 1915]]

 [[1922 1913]]

 [[1923 1913]]

 [[1924 1914]]

 [[1923 1915]]

 [[1924 1914]]

 [[1923 1913]]

 [[1922 1913]]

 [[1921 1912]]]
[[[2240  602]]

 [[2240  603]]

 [[2241  603]]

 [[2241  602]]]
[[[2259  582]]

 [[2259  583]]

 [[2260  583]]

 [[2260  582]]]
[[[2235  580]]

 [[2234  581]]

 [[2234  582]]

 [[2233  583]]

 [[2232  583]]

 [[2235  583]]

 [[2235  582]]

 [[2236  581]]

 [[2236  580]]]
[[[2230  576]]

 [[2230  578]]

 [[2231  579]]

 [[2231  578]]

 [[2232  577]]

 [[2232 