In [2]:
import cv2 as cv2   #importing opevcv
import numpy as np


symp_im = cv2.imread('symptoms/11085_right.jpeg');    #reading an image
I = symp_im.copy()
grayScale_symp_im = cv2.cvtColor(symp_im, cv2.COLOR_BGR2GRAY);  #converting the orginal image to GRAY SCALE


#RESIZE IMAGE
#symp_im_rs = cv2.resize(symp_im, (1430, 720));     #orginal image resizing
#gray_symp_im_rs = cv2.resize(grayScale_symp_im, (430, 320));    #grayscale image resizing

#SHOWING IMAGE
#cv2.imshow('symptoms image',symp_im_rs);    #orginal image
#cv2.imshow('Gray Scale - symptoms image',gray_symp_im_rs);    #gryascale image


#BINARISING & THRESHOLD SLIDER
#threshold slider code
#nothing() is called each time threshold value is updated

ret,thresh_symp_im = cv2.threshold(grayScale_symp_im, 127, 255, cv2.THRESH_BINARY_INV);   #binarising based on threshold slider
    
#contour drawing test code
image, contours, hierarchy = cv2.findContours(thresh_symp_im, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

img = cv2.drawContours(image, contours, -1, (0,0, 255), 3)

for contour in contours:
    print contour

    original = cv2.boundingRect(contour)

        
    cv2.rectangle(symp_im, (original[0], original[1]), (original[0]+original[2], original[1] + original[3]), (0,0,255), 3)
#img = cv2.putText(image, str("s"), cv2.boundingRect(contour)[:2], cv2.FONT_HERSHEY_COMPLEX, 1, [125])
#test code ends here
bin_symp_im_rs = cv2.resize(symp_im, (900, 720));    #Binary image resizing
cv2.imshow('Binarised.png', bin_symp_im_rs);    #show binary image

    


#keyboard binding function
k = cv2.waitKey(0);   
if k == 27:           #wait for ESC key to exit
    cv2.destroyAllWindows();     #destroys all windows created

[[[ 911 1919]]]
[[[ 904 1919]]]
[[[1867 1918]]

 [[1867 1919]]

 [[1868 1919]]

 [[1868 1918]]]
[[[ 664 1918]]

 [[ 664 1919]]]
[[[1921 1917]]]
[[[ 885 1917]]

 [[ 885 1919]]]
[[[ 656 1917]]

 [[ 656 1919]]

 [[ 657 1919]]

 [[ 657 1917]]]
[[[1063 1916]]

 [[1062 1917]]

 [[1064 1919]]

 [[1066 1919]]

 [[1066 1918]]

 [[1065 1917]]

 [[1065 1916]]]
[[[1056 1916]]

 [[1055 1917]]

 [[1048 1917]]

 [[1048 1918]]

 [[1047 1919]]

 [[1046 1918]]

 [[1045 1918]]

 [[1045 1919]]

 [[1048 1919]]

 [[1050 1917]]

 [[1053 1917]]

 [[1055 1919]]

 [[1057 1919]]

 [[1057 1917]]]
[[[1923 1915]]]
[[[ 672 1914]]

 [[ 672 1917]]

 [[ 671 1918]]

 [[ 671 1919]]

 [[ 673 1919]]

 [[ 673 1918]]

 [[ 672 1917]]]
[[[1923 1913]]]
[[[1136 1912]]

 [[1140 1912]]]
[[[1080 1912]]]
[[[1037 1912]]

 [[1038 1912]]

 [[1039 1913]]

 [[1040 1913]]

 [[1040 1912]]]
[[[ 992 1912]]]
[[[ 913 1912]]

 [[ 913 1919]]

 [[ 914 1919]]

 [[ 914 1917]]

 [[ 915 1916]]

 [[ 915 1912]]]
[[[ 642 1910]]

 [[ 642 1912]]

 [[ 643 

[[[1719 1283]]

 [[1719 1284]]]
[[[1642 1283]]

 [[1641 1284]]

 [[1642 1284]]]
[[[2312 1280]]

 [[2313 1280]]]
[[[1870 1280]]

 [[1870 1281]]]
[[[1765 1280]]

 [[1766 1280]]]
[[[1701 1280]]

 [[1701 1281]]

 [[1702 1281]]

 [[1702 1280]]]
[[[1859 1279]]

 [[1858 1280]]

 [[1857 1280]]

 [[1862 1280]]

 [[1861 1279]]]
[[[1805 1277]]

 [[1806 1277]]]
[[[1718 1277]]

 [[1718 1278]]]
[[[1376 1277]]]
[[[1331 1277]]]
[[[1282 1277]]

 [[1282 1278]]

 [[1281 1279]]

 [[1283 1281]]

 [[1285 1281]]

 [[1286 1280]]

 [[1287 1280]]

 [[1285 1280]]

 [[1283 1278]]

 [[1283 1277]]]
[[[1845 1276]]

 [[1846 1276]]]
[[[2080 1275]]]
[[[1634 1275]]

 [[1634 1276]]]
[[[1623 1274]]]
[[[1822 1273]]

 [[1822 1274]]

 [[1820 1276]]

 [[1819 1276]]

 [[1819 1277]]

 [[1820 1276]]

 [[1822 1276]]]
[[[1750 1273]]

 [[1750 1274]]]
[[[2082 1272]]

 [[2083 1272]]]
[[[1714 1272]]]
[[[1199 1272]]]
[[[1080 1272]]

 [[1083 1272]]]
[[[1866 1271]]

 [[1866 1272]]]
[[[1838 1269]]

 [[1839 1269]]]
[[[1822 1269]]]
[[[1730 

[[[1874  909]]]
[[[1860  909]]]
[[[2094  907]]]
[[[2087  907]]

 [[2087  908]]]
[[[2054  907]]

 [[2054  908]]

 [[2057  908]]

 [[2057  907]]]
[[[2014  907]]

 [[2014  908]]]
[[[1759  907]]

 [[1759  908]]]
[[[1520  907]]

 [[1520  908]]]
[[[1320  907]]

 [[1319  908]]

 [[1318  908]]

 [[1319  909]]

 [[1322  909]]

 [[1322  908]]

 [[1321  907]]]
[[[1844  906]]]
[[[2067  905]]

 [[2067  908]]

 [[2068  908]]

 [[2067  907]]]
[[[2034  905]]

 [[2034  909]]

 [[2034  906]]

 [[2035  905]]]
[[[1884  905]]]
[[[1860  905]]

 [[1860  906]]

 [[1861  906]]]
[[[1776  905]]]
[[[2051  904]]

 [[2051  905]]

 [[2052  905]]]
[[[2007  904]]

 [[2010  904]]]
[[[2003  904]]

 [[2003  906]]

 [[2002  907]]

 [[2002  908]]

 [[2003  907]]

 [[2003  906]]

 [[2004  905]]

 [[2004  904]]]
[[[1856  904]]]
[[[1837  904]]

 [[1837  908]]

 [[1836  909]]

 [[1837  909]]

 [[1837  907]]

 [[1838  906]]

 [[1837  905]]]
[[[1820  904]]

 [[1819  905]]

 [[1819  906]]

 [[1820  906]]]
[[[1519  904]]]
[[[1675 

[[[1671  565]]

 [[1672  565]]]
[[[1620  565]]

 [[1619  566]]

 [[1619  567]]

 [[1621  567]]

 [[1621  565]]]
[[[1599  565]]

 [[1599  567]]]
[[[2360  563]]]
[[[2282  560]]

 [[2282  567]]

 [[2281  568]]

 [[2280  568]]

 [[2282  570]]

 [[2282  568]]

 [[2283  567]]

 [[2283  560]]]
[[[1568  560]]

 [[1568  564]]

 [[1571  564]]

 [[1571  562]]

 [[1569  560]]]
[[[1475  559]]

 [[1474  560]]

 [[1472  560]]

 [[1472  567]]

 [[1471  568]]

 [[1469  568]]

 [[1469  569]]

 [[1471  571]]

 [[1471  573]]

 [[1472  574]]

 [[1472  577]]

 [[1471  578]]

 [[1469  578]]

 [[1469  583]]

 [[1472  586]]

 [[1472  587]]

 [[1471  588]]

 [[1468  588]]

 [[1471  588]]

 [[1472  589]]

 [[1478  589]]

 [[1479  588]]

 [[1480  589]]

 [[1480  591]]

 [[1482  591]]

 [[1482  590]]

 [[1481  589]]

 [[1480  589]]

 [[1479  588]]

 [[1479  586]]

 [[1480  585]]

 [[1487  585]]

 [[1488  586]]

 [[1489  586]]

 [[1489  584]]

 [[1488  584]]

 [[1487  583]]

 [[1486  583]]

 [[1484  581]]

 [[1480 