In [ ]:
import cv2 as cv2   #importing opevcv
import numpy as np


symp_im = cv2.imread('symptoms/11085_right.jpeg');    #reading an image
I = symp_im.copy()
grayScale_symp_im = cv2.cvtColor(symp_im, cv2.COLOR_BGR2GRAY);  #converting the orginal image to GRAY SCALE


#RESIZE IMAGE
#symp_im_rs = cv2.resize(symp_im, (1430, 720));     #orginal image resizing
#gray_symp_im_rs = cv2.resize(grayScale_symp_im, (430, 320));    #grayscale image resizing

#SHOWING IMAGE
#cv2.imshow('symptoms image',symp_im_rs);    #orginal image
#cv2.imshow('Gray Scale - symptoms image',gray_symp_im_rs);    #gryascale image


#BINARISING & THRESHOLD SLIDER
#threshold slider code
#nothing() is called each time threshold value is updated

ret,thresh_symp_im = cv2.threshold(grayScale_symp_im, 151, 255, cv2.THRESH_BINARY_INV);   #binarising based on threshold slider
    
#contour drawing test code
image, contours, hierarchy = cv2.findContours(thresh_symp_im, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

img = cv2.drawContours(image, contours, -1, (0,0, 255), 3)

for contour in contours:
    print contour

    original = cv2.boundingRect(contour)

        
    cv2.rectangle(symp_im, (original[0], original[1]), (original[0]+original[2], original[1] + original[3]), (0,0,255), 3)
#img = cv2.putText(image, str("s"), cv2.boundingRect(contour)[:2], cv2.FONT_HERSHEY_COMPLEX, 1, [125])
#test code ends here
bin_symp_im_rs = cv2.resize(symp_im, (900, 720));    #Binary image resizing
cv2.imshow('Binarised.png', bin_symp_im_rs);    #show binary image

    


#keyboard binding function
k = cv2.waitKey(0);   
if k == 27:           #wait for ESC key to exit
    cv2.destroyAllWindows();     #destroys all windows created

[[[2032  128]]]
[[[2067  127]]

 [[2068  127]]]
[[[2040  127]]]
[[[2065  126]]

 [[2065  127]]]
[[[2037  125]]

 [[2039  125]]]
[[[2067  124]]

 [[2068  125]]

 [[2068  124]]]
[[[2065  122]]

 [[2064  123]]

 [[2064  124]]

 [[2064  123]]]
[[[2032  122]]

 [[2032  123]]

 [[2034  123]]

 [[2034  122]]]
[[[2066  120]]]
[[[2027  120]]

 [[2028  120]]]
[[[2014  120]]

 [[2015  120]]]
[[[2060  119]]]
[[[2066  118]]]
[[[2057  118]]

 [[2057  119]]]
[[[2056  116]]]
[[[2045  116]]

 [[2044  117]]

 [[2044  119]]

 [[2047  119]]

 [[2048  120]]

 [[2051  120]]

 [[2048  120]]

 [[2047  119]]

 [[2047  117]]

 [[2046  116]]]
[[[2057  113]]

 [[2057  114]]

 [[2058  114]]

 [[2059  115]]

 [[2059  117]]

 [[2059  115]]]
[[[2049  104]]]
[[[2011  104]]

 [[2013  104]]]
[[[2041   99]]]
[[[2040   96]]

 [[2041   97]]

 [[2042   96]]

 [[2041   97]]]
[[[2008   96]]

 [[2010   96]]]
[[[1998   88]]

 [[1998   91]]

 [[1999   92]]

 [[1999   88]]]
[[[2008   86]]

 [[2007   87]]

 [[2008   87]]]
[[[2027 