In [1]:
import cv2 as cv2   #importing opevcv
import numpy as np


symp_im = cv2.imread('symptoms/11085_right.jpeg');    #reading an image
I = symp_im.copy()
grayScale_symp_im = cv2.cvtColor(symp_im, cv2.COLOR_BGR2GRAY);  #converting the orginal image to GRAY SCALE


#RESIZE IMAGE
#symp_im_rs = cv2.resize(symp_im, (1430, 720));     #orginal image resizing
#gray_symp_im_rs = cv2.resize(grayScale_symp_im, (430, 320));    #grayscale image resizing

#SHOWING IMAGE
#cv2.imshow('symptoms image',symp_im_rs);    #orginal image
#cv2.imshow('Gray Scale - symptoms image',gray_symp_im_rs);    #gryascale image


#BINARISING & THRESHOLD SLIDER
#threshold slider code
#nothing() is called each time threshold value is updated

ret,thresh_symp_im = cv2.threshold(grayScale_symp_im,150, 255, cv2.THRESH_TRUNC);   #binarising based on threshold slider
    
#contour drawing test code
image, contours, hierarchy = cv2.findContours(thresh_symp_im, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

img = cv2.drawContours(image, contours, -1, (0,0, 255), 3)

for contour in contours:
    print contour

    original = cv2.boundingRect(contour)

        
    cv2.rectangle(symp_im, (original[0], original[1]), (original[0]+original[2], original[1] + original[3]), (0,0,255), 3)
#img = cv2.putText(image, str("s"), cv2.boundingRect(contour)[:2], cv2.FONT_HERSHEY_COMPLEX, 1, [125])
#test code ends here
bin_symp_im_rs = cv2.resize(symp_im, (900, 720));    #Binary image resizing
cv2.imshow('Binarised.png', bin_symp_im_rs);    #show binary image

    


#keyboard binding function
k = cv2.waitKey(0);   
if k == 27:           #wait for ESC key to exit
    cv2.destroyAllWindows();     #destroys all windows created

[[[ 608 1918]]

 [[ 608 1919]]

 [[ 609 1919]]

 [[ 609 1918]]]
[[[1943 1917]]

 [[1942 1918]]

 [[1941 1918]]

 [[1942 1919]]

 [[1945 1919]]

 [[1945 1918]]

 [[1944 1918]]]
[[[1948 1914]]

 [[1948 1915]]

 [[1949 1915]]

 [[1949 1914]]]
[[[ 612 1914]]

 [[ 612 1915]]

 [[ 613 1914]]]
[[[ 608 1914]]

 [[ 608 1915]]

 [[ 609 1915]]

 [[ 609 1914]]]
[[[1950 1912]]

 [[1951 1912]]]
[[[1943 1911]]

 [[1943 1912]]]
[[[ 608 1905]]

 [[ 609 1905]]]
[[[1955 1903]]]
[[[ 592 1902]]

 [[ 592 1903]]

 [[ 593 1903]]

 [[ 593 1902]]]
[[[1957 1901]]

 [[1958 1902]]

 [[1959 1902]]

 [[1958 1902]]]
[[[1959 1900]]]
[[[ 576 1884]]]
[[[1986 1879]]]
[[[ 569 1878]]

 [[ 568 1879]]]
[[[ 568 1875]]

 [[ 568 1876]]]
[[[2001 1870]]

 [[2001 1871]]]
[[[ 550 1870]]

 [[ 550 1871]]

 [[ 553 1871]]

 [[ 553 1870]]]
[[[2014 1868]]

 [[2015 1869]]

 [[2015 1868]]]
[[[ 544 1866]]

 [[ 544 1867]]

 [[ 545 1867]]

 [[ 545 1866]]]
[[[ 558 1865]]

 [[ 558 1867]]]
[[[2015 1864]]

 [[2014 1865]]

 [[2015 1865]]]
[[[2007 